apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: amazing-next-app-pipeline
spec:
  params:
    - name: source-repo
      type: string
      description: Source code repository
  workspaces:
    - name: amazing-next-app-workspace
  tasks:
    - name: clone-repository
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: "$(params.source-repo)"
      workspaces:
        - name: output
          workspace: amazing-next-app-workspace