apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: amazing-next-app-pipeline-run-
spec:
  pipelineRef:
    name: amazing-next-app-pipeline
  params:
    - name: source-repo
      value: https://github.com/alexseymour1997/amazing-next-app
  workspaces:
    - name: amazing-next-app-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi